"""First migration

Revision ID: d1d5c7c7a2b3
Revises: 
Create Date: 2023-11-28 00:24:52.272282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d5c7c7a2b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('merchart_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_code', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_brand', sa.String(length=200), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('product_promo_price', sa.Float(), nullable=True),
    sa.Column('product_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Product')
    # ### end Alembic commands ###
